### PR TITLE
ci: update distro

### PR DESCRIPTION
**Pull request by wep21**
- update distros in ci

### CODE REVIEW

**Comment by Scout22** [comment]
@xmfcx when do you think you could accept this edit.
We are reliant on socketcan and this is currently blocking our transition to ROS2 jazzy

**Review by xmfcx — APPROVED** [review]
Thanks for the update!

**Comment by wep21** [comment]
@xmfcx please create a new tag and do bloom-release for jazzy and rolling because it still fails.
https://build.ros2.org/job/Rbin_uN64__ros2_socketcan__ubuntu_noble_amd64__binary/

**Comment by xmfcx** [comment]
@wep21 I don't know how this repository is connected to the ROS build farm.

And I've never done a bloom-release before. (Where do you do that?)

I've also found this: https://github.com/ros2-gbp/ros2_socketcan-release/ that has commits from you (without any pull requests) and I also don't have access to that repository as well.

What should I do?

I've created this https://github.com/autowarefoundation/ros2_socketcan/releases/tag/1.3.0 tag if it is going to be useful.

**Comment by xmfcx** [comment]
I think I should also add myself to the release team like you added @mitsudome-r to your place here:
- https://github.com/ros2-gbp/ros2-gbp-github-org/pull/422

**Comment by JWhitleyWork** [comment]
@xmfcx Hey, old friend. Here is the basic connection/process for release:

This repository is not directly connected to the build farm. However, https://github.com/ros2-gbp/ros2_socketcan-release/ is and it contains branches with copies of this repository at specific timepoints/tags. In order to release a new version of this repository for a specific version of ROS2, you must do the following:

1. Install `python3-catkin-pkg` and `python3-bloom` from the ROS2 `apt` repo.
2. In this repository, on the branch you intend to release, run `catkin_generate_changelog`.
3. Clean up and update the contents of the `CHANGELOG.rst` file for each package in the repo. By default, they will contain the commit messages of all commits since the last release.
4. Commit and push the updated changelogs.
5. In this repository, on the branch you intend to release, run `catkin_prepare_release`. By default this will bump the release by a major version - you can change this with the `--bump` argument. This will update the version in `package.xml` and tag the current commit with the new version.
6. Run `bloom-release --track <ros2_distro> --ros-distro <ros2_distro> ros2_socketcan`. Since release tracks have already been set up for this repository for the currently-available ROS2 distros and because the tracks are already configured to point to this repository and the `main` branch to look for tags, it will automatically find the new release tag, create a bunch of branches on https://github.com/ros2-gbp/ros2_socketcan-release/, and then create a Pull Request on https://github.com/ros/rosdistro which will update the information in the `distribution.yaml` file for the selected ROS2 distro which `rosdep` uses to let the build farm know about the latest available release for a given package.

If you are updating releases for multiple ROS2 distros based on the same, new release on this repo, you only need to run the `bloom-release` step for each ROS2 distro.

Here is the source of most of this information (but in a more confusing layout): https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

Hit me up if you have any questions.

**Comment by g-arjones** [comment]
Any plans to release this on Jazzy? Thanks!

**Comment by xmfcx** [comment]
Oh no I completely forgot about this, Thanks @JWhitleyWork for the detailed explanation. Now that I'm a part of the release team, I will follow your instructions to release this for jazzy.

Sorry everyone for looking over this :bowing_man:

**Comment by g-arjones** [comment]
Thanks!

**Comment by xmfcx** [comment]
@wep21 @JWhitleyWork @g-arjones
I hope I did things correctly, here is the list of PRs to the releases:
- https://github.com/autowarefoundation/ros2_socketcan/pull/49#issuecomment-2231596990

Thank you for your patience.

**Comment by g-arjones** [comment]
It looks like you did: https://repo.ros2.org/status_page/ros_jazzy_default.html?q=ros2_socketcan

We just have to wait for a sync now. Thanks!

**Pull request merged**
